### ISSUE TITLE
Build component (Candlestick-Chart) 

### ISSUE THREAD

**Issue by roabram** [roabram/tradehammer#11]
#### Description

Build the first component to show the candlestick chart of a single stock or crypto. 

#### Screenshots

![image](https://user-images.githubusercontent.com/82370347/122018124-da045a80-cdc2-11eb-8786-389fa29ef7d0.png)

#### To Reproduce

Show 15min chart of AAPL. 

#### Tasks

Show

- [x] Build the frame 
- [x] define the colors as global variables 
- [x] Build 
- [x] Build the Candlestick Chart Pattern with test data
- [x] Style the Candlestick Chart Pattern
