### ISSUE TITLE
Component: tradeIn Button 

### ISSUE THREAD

**Issue by roabram** [roabram/tradehammer#14]
#### Description

Build the tradeIn Button component

#### Screenshots

![image](https://user-images.githubusercontent.com/82370347/122358910-647cc380-cf55-11eb-83e7-bb513293bae8.png)

#### To Reproduce

Link to the main page 

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Style the component 
- [x] insert the text field 
- [x] Add functionality (link)
