### ISSUE TITLE
Build the search Button, with the search input field ..

### ISSUE THREAD

**Issue by roabram** [roabram/tradehammer#16]
#### Description

Build the search "Button"  and the search input field 

#### Screenshots

![image](https://user-images.githubusercontent.com/82370347/122379760-70718100-cf67-11eb-9650-e6a886c129cd.png)
![image](https://user-images.githubusercontent.com/82370347/122379359-15d82500-cf67-11eb-8411-c12d05b52e9a.png)

#### Tasks

- [ ] Build the search Button 
- [ ] Style search Button
- [ ] Build the search input field 
- [ ] Style search input field
- [ ] Build the functionality with use State in one component
