### ISSUE TITLE
Build the "Home"- Page 

### ISSUE THREAD

**Issue by roabram** [roabram/tradehammer#19]
#### Description

Build the home-Landigpage Page 

#### Screenshots

![image](https://user-images.githubusercontent.com/82370347/122637488-38954580-d0ef-11eb-8d2f-1bacd9012cdf.png)

#### Tasks

Build the Home Page

- [x] Add Logo 
- [x] Add Title
- [x] Add SearchFunction component
- [x] Add Chart component 
- [ ] Style with css
