### ISSUE TITLE
Build samples.http 

### ISSUE THREAD

**Issue by roabram** [roabram/tradehammer#3]
#### Add sample.HTTP

Add sample HTTP requests with custom PORT and Proxy 

#### To Reproduce

Sample: 
[Photoplay](https://github.com/lmachens/photoplay/pull/49/commits/650917bc2d1d772c4226adaa6be41c02c090e95b)

#### Tasks

- [x] Add Proxy to API 
- [x] Build sample.HTTP 
- [x] Use sample.HTTP
- [x] Check receiving data from sample.HTTP
