### ISSUE TITLE
Define API 

### ISSUE THREAD

**Issue by roabram** [roabram/tradehammer#4]
#### Define API 

Check API and get all necessary information which is needed to fetch the data. 

#### Tasks

- [x] Structure of the api
- [x] How to get and send requests
- [x] API key needed? 
- [x] how many requests are possible
