### ISSUE TITLE
Build "API".ts 

### ISSUE THREAD

**Issue by roabram** [roabram/tradehammer#5]
#### Outsource necessary functions for the API in a .ts file 

Create all necessary functions in a *API*.ts to outsource them. 

#### Sample
[Sample](https://github.com/lmachens/photoplay/pull/49/commits/330d451ffb3053d77c89431820fc60d3af3ca7cc)

#### Tasks

- [x] Create BASE_URL
- [x] Create fetch function
- [ ] Create specific functions using the fetch function
